import hljs from 'highlight.js';
import escapeHtml from 'escape-html';

const ext = new Set([
  '1c',
  'abnf',
  'accesslog',
  'ada',
  'armasm', 'arm',
  'avrasm',
  'actionscript', 'as',
  'apache', 'apacheconf',
  'applescript', 'osascript',
  'asciidoc', 'adoc',
  'aspectj',
  'autohotkey',
  'autoit',
  'awk', 'mawk', 'nawk', 'gawk',
  'axapta',
  'bash', 'sh', 'zsh',
  'basic',
  'bnf',
  'brainfuck', 'bf',
  'cs', 'csharp',
  'cpp', 'c', 'cc', 'h', 'c++', 'h++', 'hpp',
  'cal',
  'cos', 'cls',
  'cmake', 'cmake.in',
  'coq',
  'csp',
  'css',
  'capnproto', 'capnp',
  'clojure', 'clj',
  'coffeescript', 'coffee', 'cson', 'iced',
  'crmsh', 'crm', 'pcmk',
  'crystal', 'cr',
  'd',
  'dns', 'zone', 'bind',
  'dos', 'bat', 'cmd',
  'dart',
  'delphi', 'dpr', 'dfm', 'pas', 'pascal', 'freepascal,lazarus', 'lpr', 'lfm',
  'diff', 'patch',
  'django', 'jinja',
  'dockerfile', 'docker',
  'dsconfig',
  'dts',
  'dust', 'dst',
  'ebnf',
  'elixir',
  'elm',
  'erlang', 'erl',
  'excel', 'xls', 'xlsx',
  'fsharp', 'fs',
  'fix',
  'fortran', 'f90', 'f95',
  'gcode', 'nc',
  'gams', 'gms',
  'gauss', 'gss',
  'gherkin',
  'go', 'golang',
  'golo', 'gololang',
  'gradle',
  'groovy',
  'xml', 'html', 'xhtml', 'rss', 'atom', 'xjb', 'xsd', 'xsl', 'plist',
  'http', 'https',
  'haml',
  'handlebars', 'hbs', 'html.hbs', 'html.handlebars',
  'haskell', 'hs',
  'haxe', 'hx',
  'ini',
  'inform7', 'i7',
  'irpf90',
  'json',
  'java', 'jsp',
  'javascript', 'js', 'jsx',
  'lasso', 'ls', 'lassoscript',
  'less',
  'ldif',
  'lisp',
  'livecodeserver',
  'livescript', 'ls',
  'lua',
  'makefile', 'mk', 'mak',
  'markdown', 'md', 'mkdown', 'mkd',
  'mathematica', 'mma',
  'matlab',
  'maxima',
  'mel',
  'mercury',
  'mizar',
  'mojolicious',
  'monkey',
  'moonscript', 'moon',
  'nsis',
  'nginx', 'nginxconf',
  'nimrod', 'nim',
  'nix',
  'ocaml', 'ml',
  'objectivec', 'mm', 'objc', 'obj-c',
  'glsl',
  'openscad', 'scad',
  'ruleslanguage',
  'oxygene',
  'pf', 'pf.conf',
  'php', 'php3', 'php4', 'php5', 'php6',
  'parser3',
  'perl', 'pl', 'pm',
  'pony',
  'powershell', 'ps',
  'processing',
  'prolog',
  'protobuf',
  'puppet', 'pp',
  'python', 'py', 'gyp',
  'profile',
  'k', 'kdb',
  'qml',
  'r',
  'rib',
  'rsl',
  'graph', 'instances',
  'ruby', 'rb', 'gemspec', 'podspec', 'thor', 'irb',
  'rust', 'rs',
  'scss',
  'sql',
  'p21', 'step', 'stp',
  'scala',
  'scheme',
  'scilab', 'sci',
  'smali',
  'smalltalk', 'st',
  'stan',
  'stata',
  'stylus', 'styl',
  'subunit',
  'swift',
  'tap',
  'tcl', 'tk',
  'tex',
  'thrift',
  'tp',
  'twig', 'craftcms',
  'typescript', 'ts',
  'vbnet', 'vb',
  'vbscript', 'vbs',
  'vhdl',
  'vala',
  'verilog', 'v',
  'vim',
  'x86asm',
  'xl', 'tao',
  'xpath', 'xq',
  'zephir', 'zep',
]);

let dom = null;

export default {
  ext,
  bind(target) {
    dom = target;
  },
  render(input, path) {
    dom.innerHTML = `<pre><code class="${path.split('.').pop().toLowerCase()}">${escapeHtml(input)}</code></pre>`;
    hljs.highlightBlock(dom);
  },
};
